-- =====================================================================
-- Limpieza de listas por sucursal (estado real: nombres en MAYÚSCULAS)
-- Deja a cada sucursal EXACTAMENTE su lista §5 y desactiva el resto.
-- Idempotente. Correr en el SQL editor.
-- Conteos: Del Valle 21 · Las Brisas 17 · Cervecería 19 · Solares 21
-- =====================================================================

-- 1) Asignar/activar la lista correcta por sucursal (orden incluido).
INSERT INTO public.insumo_sucursal (insumo_id, sucursal_id, orden, activo)
SELECT i.id, s.id, m.orden, true
FROM (VALUES
    ('Del Valle','CAMARON 61-70',1),
    ('Del Valle','CAMARON 31-35',2),
    ('Del Valle','CAMARON 21-25',3),
    ('Del Valle','PULPO 2-4',4),
    ('Del Valle','ATÚN MEDALLON pz',5),
    ('Del Valle','MARLIN AHUMADO K.',6),
    ('Del Valle','ROBALO (chicharrón)',7),
    ('Del Valle','ROBALO (filete)',8),
    ('Del Valle','SIERRA',9),
    ('Del Valle','CAMARON VAPOR 25 a 30 gr',10),
    ('Del Valle','CAMARON 7 A 11 GR',11),
    ('Del Valle','CAMARON 12 - 25 GR',12),
    ('Del Valle','CAMARON SECO K.',13),
    ('Del Valle','BOLSAS OSTIÓN',14),
    ('Del Valle','CALLO DE HACHA',15),
    ('Del Valle','PESCADO P/SARANDEAR',16),
    ('Del Valle','FILETE DE RES',17),
    ('Del Valle','COSTILLA DE CERDO',18),
    ('Del Valle','ALITAS',19),
    ('Del Valle','BONELESS',20),
    ('Del Valle','PIZZAS',21),
    ('Las Brisas','CAMARON 61-70',1),
    ('Las Brisas','CAMARON 31-35',2),
    ('Las Brisas','CAMARON 21-25',3),
    ('Las Brisas','PULPO 2-4',4),
    ('Las Brisas','ATÚN MEDALLON pz',5),
    ('Las Brisas','MARLIN AHUMADO K.',6),
    ('Las Brisas','ROBALO (chicharrón)',7),
    ('Las Brisas','ROBALO (filete)',8),
    ('Las Brisas','SIERRA',9),
    ('Las Brisas','CAMARON VAPOR 25 a 30 gr',10),
    ('Las Brisas','CAMARON 7 A 11 GR',11),
    ('Las Brisas','CAMARON 12 - 25 GR',12),
    ('Las Brisas','CAMARON SECO K.',13),
    ('Las Brisas','BOLSAS OSTIÓN',14),
    ('Las Brisas','CALLO DE HACHA',15),
    ('Las Brisas','BONELESS',20),
    ('Las Brisas','PIZZAS',21),
    ('Cervecería','CAMARON 61-70',1),
    ('Cervecería','CAMARON 31-35',2),
    ('Cervecería','CAMARON 21-25',3),
    ('Cervecería','PULPO 2-4',4),
    ('Cervecería','ATÚN MEDALLON pz',5),
    ('Cervecería','MARLIN AHUMADO K.',6),
    ('Cervecería','ROBALO (chicharrón)',7),
    ('Cervecería','ROBALO (filete)',8),
    ('Cervecería','SIERRA',9),
    ('Cervecería','CAMARON VAPOR 25 a 30 gr',10),
    ('Cervecería','CAMARON 7 A 11 GR',11),
    ('Cervecería','CAMARON 12 - 25 GR',12),
    ('Cervecería','CAMARON SECO K.',13),
    ('Cervecería','BOLSAS OSTIÓN',14),
    ('Cervecería','CALLO DE HACHA',15),
    ('Cervecería','FILETE DE RES',17),
    ('Cervecería','ALITAS',19),
    ('Cervecería','BONELESS',20),
    ('Cervecería','PIZZAS',21),
    ('Solares','CAMARON 61-70',1),
    ('Solares','CAMARON 31-35',2),
    ('Solares','CAMARON 21-25',3),
    ('Solares','PULPO 2-4',4),
    ('Solares','ATÚN MEDALLON pz',5),
    ('Solares','MARLIN AHUMADO K.',6),
    ('Solares','ROBALO (chicharrón)',7),
    ('Solares','ROBALO (filete)',8),
    ('Solares','SIERRA',9),
    ('Solares','CAMARON VAPOR 25 a 30 gr',10),
    ('Solares','CAMARON 7 A 11 GR',11),
    ('Solares','CAMARON 12 - 25 GR',12),
    ('Solares','CAMARON SECO K.',13),
    ('Solares','BOLSAS OSTIÓN',14),
    ('Solares','CALLO DE HACHA',15),
    ('Solares','PESCADO P/SARANDEAR',16),
    ('Solares','FILETE DE RES',17),
    ('Solares','COSTILLA DE CERDO',18),
    ('Solares','ALITAS',19),
    ('Solares','BONELESS',20),
    ('Solares','PIZZAS',21)
) AS m(sucursal, nombre, orden)
JOIN public.insumos i    ON i.nombre = m.nombre
JOIN public.sucursales s ON s.nombre = m.sucursal
ON CONFLICT (insumo_id, sucursal_id)
  DO UPDATE SET activo = true, orden = EXCLUDED.orden;

-- 2) Quitar de cada sucursal todo lo que NO esté en su lista (incluye los 138 no-proteína).
DELETE FROM public.insumo_sucursal isuc
USING public.insumos i, public.sucursales s
WHERE isuc.insumo_id = i.id
  AND isuc.sucursal_id = s.id
  AND NOT EXISTS (
    SELECT 1 FROM (VALUES
    ('Del Valle','CAMARON 61-70',1),
    ('Del Valle','CAMARON 31-35',2),
    ('Del Valle','CAMARON 21-25',3),
    ('Del Valle','PULPO 2-4',4),
    ('Del Valle','ATÚN MEDALLON pz',5),
    ('Del Valle','MARLIN AHUMADO K.',6),
    ('Del Valle','ROBALO (chicharrón)',7),
    ('Del Valle','ROBALO (filete)',8),
    ('Del Valle','SIERRA',9),
    ('Del Valle','CAMARON VAPOR 25 a 30 gr',10),
    ('Del Valle','CAMARON 7 A 11 GR',11),
    ('Del Valle','CAMARON 12 - 25 GR',12),
    ('Del Valle','CAMARON SECO K.',13),
    ('Del Valle','BOLSAS OSTIÓN',14),
    ('Del Valle','CALLO DE HACHA',15),
    ('Del Valle','PESCADO P/SARANDEAR',16),
    ('Del Valle','FILETE DE RES',17),
    ('Del Valle','COSTILLA DE CERDO',18),
    ('Del Valle','ALITAS',19),
    ('Del Valle','BONELESS',20),
    ('Del Valle','PIZZAS',21),
    ('Las Brisas','CAMARON 61-70',1),
    ('Las Brisas','CAMARON 31-35',2),
    ('Las Brisas','CAMARON 21-25',3),
    ('Las Brisas','PULPO 2-4',4),
    ('Las Brisas','ATÚN MEDALLON pz',5),
    ('Las Brisas','MARLIN AHUMADO K.',6),
    ('Las Brisas','ROBALO (chicharrón)',7),
    ('Las Brisas','ROBALO (filete)',8),
    ('Las Brisas','SIERRA',9),
    ('Las Brisas','CAMARON VAPOR 25 a 30 gr',10),
    ('Las Brisas','CAMARON 7 A 11 GR',11),
    ('Las Brisas','CAMARON 12 - 25 GR',12),
    ('Las Brisas','CAMARON SECO K.',13),
    ('Las Brisas','BOLSAS OSTIÓN',14),
    ('Las Brisas','CALLO DE HACHA',15),
    ('Las Brisas','BONELESS',20),
    ('Las Brisas','PIZZAS',21),
    ('Cervecería','CAMARON 61-70',1),
    ('Cervecería','CAMARON 31-35',2),
    ('Cervecería','CAMARON 21-25',3),
    ('Cervecería','PULPO 2-4',4),
    ('Cervecería','ATÚN MEDALLON pz',5),
    ('Cervecería','MARLIN AHUMADO K.',6),
    ('Cervecería','ROBALO (chicharrón)',7),
    ('Cervecería','ROBALO (filete)',8),
    ('Cervecería','SIERRA',9),
    ('Cervecería','CAMARON VAPOR 25 a 30 gr',10),
    ('Cervecería','CAMARON 7 A 11 GR',11),
    ('Cervecería','CAMARON 12 - 25 GR',12),
    ('Cervecería','CAMARON SECO K.',13),
    ('Cervecería','BOLSAS OSTIÓN',14),
    ('Cervecería','CALLO DE HACHA',15),
    ('Cervecería','FILETE DE RES',17),
    ('Cervecería','ALITAS',19),
    ('Cervecería','BONELESS',20),
    ('Cervecería','PIZZAS',21),
    ('Solares','CAMARON 61-70',1),
    ('Solares','CAMARON 31-35',2),
    ('Solares','CAMARON 21-25',3),
    ('Solares','PULPO 2-4',4),
    ('Solares','ATÚN MEDALLON pz',5),
    ('Solares','MARLIN AHUMADO K.',6),
    ('Solares','ROBALO (chicharrón)',7),
    ('Solares','ROBALO (filete)',8),
    ('Solares','SIERRA',9),
    ('Solares','CAMARON VAPOR 25 a 30 gr',10),
    ('Solares','CAMARON 7 A 11 GR',11),
    ('Solares','CAMARON 12 - 25 GR',12),
    ('Solares','CAMARON SECO K.',13),
    ('Solares','BOLSAS OSTIÓN',14),
    ('Solares','CALLO DE HACHA',15),
    ('Solares','PESCADO P/SARANDEAR',16),
    ('Solares','FILETE DE RES',17),
    ('Solares','COSTILLA DE CERDO',18),
    ('Solares','ALITAS',19),
    ('Solares','BONELESS',20),
    ('Solares','PIZZAS',21)
    ) AS m(sucursal, nombre, orden)
    WHERE m.sucursal = s.nombre AND m.nombre = i.nombre
  );

-- 3) Desactivar del catálogo todo lo que no sea proteína; activar las proteínas.
UPDATE public.insumos SET activo = false
WHERE nombre NOT IN (
    'CAMARON 61-70',
    'CAMARON 31-35',
    'CAMARON 21-25',
    'PULPO 2-4',
    'ATÚN MEDALLON pz',
    'MARLIN AHUMADO K.',
    'ROBALO (chicharrón)',
    'ROBALO (filete)',
    'SIERRA',
    'CAMARON VAPOR 25 a 30 gr',
    'CAMARON 7 A 11 GR',
    'CAMARON 12 - 25 GR',
    'CAMARON SECO K.',
    'BOLSAS OSTIÓN',
    'CALLO DE HACHA',
    'PESCADO P/SARANDEAR',
    'FILETE DE RES',
    'COSTILLA DE CERDO',
    'ALITAS',
    'BONELESS',
    'PIZZAS'
);
UPDATE public.insumos SET activo = true
WHERE nombre IN (
    'CAMARON 61-70',
    'CAMARON 31-35',
    'CAMARON 21-25',
    'PULPO 2-4',
    'ATÚN MEDALLON pz',
    'MARLIN AHUMADO K.',
    'ROBALO (chicharrón)',
    'ROBALO (filete)',
    'SIERRA',
    'CAMARON VAPOR 25 a 30 gr',
    'CAMARON 7 A 11 GR',
    'CAMARON 12 - 25 GR',
    'CAMARON SECO K.',
    'BOLSAS OSTIÓN',
    'CALLO DE HACHA',
    'PESCADO P/SARANDEAR',
    'FILETE DE RES',
    'COSTILLA DE CERDO',
    'ALITAS',
    'BONELESS',
    'PIZZAS'
);

-- 4) Niveles par estimados (solo donde estén vacíos; no pisa lo capturado).
WITH par(nombre, valor) AS (VALUES
    ('CAMARON 61-70',8),
    ('CAMARON 31-35',8),
    ('CAMARON 21-25',8),
    ('PULPO 2-4',5),
    ('ATÚN MEDALLON pz',20),
    ('MARLIN AHUMADO K.',4),
    ('ROBALO (chicharrón)',6),
    ('ROBALO (filete)',6),
    ('SIERRA',5),
    ('CAMARON VAPOR 25 a 30 gr',6),
    ('CAMARON 7 A 11 GR',5),
    ('CAMARON 12 - 25 GR',6),
    ('CAMARON SECO K.',3),
    ('BOLSAS OSTIÓN',10),
    ('CALLO DE HACHA',4),
    ('PESCADO P/SARANDEAR',10),
    ('FILETE DE RES',8),
    ('COSTILLA DE CERDO',8),
    ('ALITAS',10),
    ('BONELESS',10),
    ('PIZZAS',12)
)
UPDATE public.insumo_sucursal isuc
SET nivel_par = p.valor
FROM public.insumos i, par p
WHERE isuc.insumo_id = i.id
  AND i.nombre = p.nombre
  AND isuc.nivel_par IS NULL;
